BEGIN;
CREATE TABLE IF NOT EXISTS favorites(
   user_id serial PRIMARY KEY,
   content VARCHAR (255) NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
