BEGIN;
CREATE TABLE IF NOT EXISTS favorites(
   user_id  INTEGER UNIQUE NOT NULL,
   age INTEGER DEFAULT 0 NOT NULL,
   sex INTEGER DEFAULT 0 NOT NULL,
   game INTEGER DEFAULT 0 NOT NULL,
   sport INTEGER DEFAULT 0 NOT NULL,
   book INTEGER DEFAULT 0 NOT NULL,
   travel INTEGER DEFAULT 0 NOT NULL,
   internet INTEGER DEFAULT 0 NOT NULL,
   anime INTEGER DEFAULT 0 NOT NULL,
   movie INTEGER DEFAULT 0 NOT NULL,
   music INTEGER DEFAULT 0 NOT NULL,
   gourmet INTEGER DEFAULT 0 NOT NULL,
   muscle INTEGER DEFAULT 0 NOT NULL,
   camp INTEGER DEFAULT 0 NOT NULL,
   tv INTEGER DEFAULT 0 NOT NULL,
   cook INTEGER DEFAULT 0 NOT NULL
);
COMMIT;
