BEGIN;
CREATE TABLE IF NOT EXISTS users(
   user_id serial PRIMARY KEY,
   username VARCHAR (255) NOT NULL,
   password VARCHAR (255) NOT NULL,
   email VARCHAR (255) UNIQUE NOT NULL
   age INTEGER
);
COMMIT;
