BEGIN;
CREATE TABLE IF NOT EXISTS user_favorite(
   user_id INTEGER,
   favorite_id INTEGER,
   created_at TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
