BEGIN;
CREATE TABLE IF NOT EXISTS users_compatibility(
   id serial PRIMARY KEY,
   user_from_id VARCHAR (255) NOT NULL,
   user_to_id VARCHAR (255) NOT NULL,
   star VARCHAR (255) UNIQUE NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
