BEGIN;
CREATE TABLE IF NOT EXISTS favorites(
   id  BIGSERIAL PRIMARY KEY,
   content VARCHAR (255) NOT NULL,
   updated_at BIGINT DEFAULT 0 NOT NULL,
   created_at BIGINT DEFAULT 0 NOT NULL,
   deleted_at BIGINT DEFAULT 0 NOT NULL
);
COMMIT;
